name: Build

on:
  pull_request:
    paths:
      - 'backend/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Make gradlew executable
        run: chmod +x backend/gradlew

      - name: Set up JDK17 + Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          java-version: 17
          distribution: temurin
          gradle-wrapper-directory: backend
          cache-read-only: false

      - name: Build & test
        working-directory: backend
        run: ./gradlew clean build
